check50:
  checks:
    tip:
      - run: python3 tip.py
        stdin: 86.40\n4\n15
        stdout: |
          Total Bill: $99.36
          Price per person: $24.84
        exit: 0
    banner:
      - run: python3 banner.py
        stdin: _\nhello\n
        stdout: |
          ______________________
          _       hello        _
          ______________________
        exit: 0
    digits:
      - run: python3 digits.py
        stdin: 4829
        stdout: 23
        exit: 0
    username:
      - run: python3 username.py
        stdin: Allison
        stdin: Smith
        stdin: 2008
        stdout: |
          username: allsmi08
          password: SONITH18
        exit: 0
    bintodec:
      - run: python3 bintodec.py
        stdin: 01101101
        stdout: 109
        exit: 0
    swapvar:
      - run: python3 swapvar.py
        stdin: 3
        stdin: 5
        stdout: |
          x = 5
          y = 3
        exit: 0
  files: &check50_files
    - !exclude "*"
    - !include tip.py
    - !include banner.py
    - !include digits.py
    - !include username.py
    - !include bintodec.py
    - !include swapvar.py
submit50:
  files: *check50_files
