check50:
  checks:
      hello:
        - run: python hello.py
          stdin: Hello, world!
          stdout: hello, world!
  files: &check50_files
    - !exclude "*"
    - !require hello.py
submit50:
  files: *check50_files
