check50:
  checks:
    hello world:
      - run: python3 hello.py
        stdout: Hello, world!
        exit: 0
    indoor:
      - run: python3 indoor.py
        stdin: Hello, world!
        stdout: hello, world!
        exit: 0
    seconds:
      - run: python3 seconds.py
        stdout: |
          Days: 2
          Hours: 7
          Minutes: 33
          Seconds: 20
        exit: 0
files: &check50_files
    - !exclude "*"
    - !require hello.py
    - !require indoor.py
    - !require seconds.py
submit50:
  files: *check50_files
