check50:
  checks:
      indoor:
        - run: python indoor.py
          stdin: Hello, world!
          stdout: hello, world!1
  files: &check50_files
    - !exclude "*"
    - !require indoor.py
submit50:
  files: *check50_files
