check50:
  checks:
      indoor:
        - run: python indoor.py
          stdin: Hello, world!
          stdout: hello, world!
      seconds:
        - run: python seconds.py
          stdin: 200000
          stdout: Days: 2
  files: &check50_files
    - !exclude "*"
    - !require indoor.py
    - !require seconds.py
submit50:
  files: *check50_files
