check50:
  checks:
      hello world:
        - run: python hello.py
          stdout: Hello, world!
          exit: 0
  files: &check50_files
    - !exclude "*"
    - !require hello.py
submit50:
  files: *check50_files
